name: ci

on:
  push:
    branches:
      - development

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
        contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Start tests
        run: make test
